# Generated by Django 4.0.5 on 2022-07-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cat',
            new_name='category',
        ),
    ]
