# Generated by Django 4.0.5 on 2022-07-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_post_add_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
    ]
