# Generated by Django 4.0.5 on 2022-07-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
    ]
